### ISSUE TITLE
ライセンスの問題

### ISSUE THREAD

**Issue by nnn1590** [Aoichaan0513/Discord-Rich-Presence#1]
`README.md`には
https://github.com/Aoichaan0513/Discord-Rich-Presence/blob/31e114bbc9da98246bd1d7ea25a12c3c31fa2e3e/README.md#L13
と書いてありますが[`LICENSE`](https://github.com/Aoichaan0513/Discord-Rich-Presence/blob/a2954f7985b271c5eb1cc34a4fb5e21c6ad968a9/LICENSE)ではMIT/X11ライセンスになっています。

MIT/X11ライセンスは再配布も改造も許可しているライセンスですので修正してもらえませんか？

**Comment by Aoichaan0513** [comment]
半年以上も放置してしまい大変申し訳ございませんでした。
現時点を以て修正いたしました。
